shadowhand/latitude

- CHANGELOG.md
- src/Postgres/Traits/CanReturnAfterExecute.php
- tests/Postgres/UpdateQueryTest.php
If a Postgres query that supported RETURNING was built without defining
the RETURNING values, it would produce invalid SQL.
> Prevent invalid SQL with empty RETURNING

- CHANGELOG.md
- README.md
- src/Traits/CanReplaceBooleanAndNullValues.php
- tests/InsertQueryTest.php
Using expressions such as `NOW()` in inserts and updates is common
practice for handling timestamps. Other applications exist.
> Allow expressions in insert and update statements

- .travis.yml
Adding cache speeds up composer.
Removed `composer self-update` because Travis already does it.
Switched to `composer test` because why not.
> Optimize Travis builds

- CHANGELOG.md
- src/InsertQuery.php
- src/Traits/CanReplaceBooleanAndNullValues.php
- src/UpdateQuery.php
- tests/InsertQueryTest.php
Due to how null, boolean, and expression values were handled in INSERT
and UPDATE queries, compiling the same query multiple times would result
in different results.
Fixes #6
> Fix multiple compiles of insert and update

- src/Traits/CanReplaceBooleanAndNullValues.php
When generating SQL, null values (and boolean values) are included in the SQL, and not included in the parameters.
By filtering out these parameters, their original index in the array is preserved, which leads a non-sequential keys. It seems PDOStatement::execute() isn't able to figure this out. 
Returning a new array with only the array values fixes this issue. 
HTH
> (fix) Reset array keys for params()

- src/Identifier.php
- src/SelectQuery.php
- tests/SelectQueryTest.php
Extend the orderBy method to allow ordering by Expression as well
> (fix) Enabling order by expression

- CHANGELOG.md
- src/QueryFactory.php
- tests/QueryFactoryTest.php
Makes it easier to mock `QueryFactory` and set up dependency injection.
> Use common as the default engine for QueryFactory

- README.md
- src/InsertQuery.php
- src/ValueList.php
- tests/ConditionsTest.php
- tests/ValueListTest.php
It makes no sense to have unpacked arguments for a value list, since the
construction will almost certainly never be hard coded.
Similarly, it makes no sense to not wrap a value list in parenthesis.
> Update value list internals

- src/SelectQuery.php
- tests/SelectQueryTest.php
```php
use Latitude\QueryBuilder\SelectQuery;
use Latitude\QueryBuilder\Expression;
$select = SelectQuery::make(
Expression::make('DATE(created_at) AS %s', 'date')
)
->from('users')
->groupBy(Expression::make('DATE(created_at)')); 
echo $select->sql(); // Should be SELECT DATE(created_at) AS date FROM users GROUP BY DATE(created_at)
// TypeError: Argument 1 passed to Latitude\QueryBuilder\SelectQuery::groupBy() must be of the type string, object given
```
> Fixed ability grouping by expressions

- README.md
- src/MySQL/DeleteQuery.php
- src/MySQL/UpdateQuery.php
- src/QueryFactory.php
- src/SelectQuery.php
- src/Traits/CanLimit.php
- src/Traits/CanOrderBy.php
- tests/MySQL/DeleteQueryTest.php
- tests/MySQL/UpdateQueryTest.php
- tests/QueryFactoryTest.php
MySQL supports `ORDER BY` and `LIMIT` in `UPDATE` and `DELETE` queries. This PR adds support for that.
See https://dev.mysql.com/doc/refman/5.5/en/update.html and https://dev.mysql.com/doc/refman/5.5/en/delete.html for more information about this feature.
> add ORDER BY and LIMIT support to UPDATE and DELETE queries in MySQL

- CHANGELOG.md
- src/ValueList.php
- tests/ValueListTest.php
The value list should always be a list of values, never a map.
Passing a map would cause type errors if the map used string keys.
> Fix value list values

- composer.json
- psalm.xml
- src/Conditions.php
- src/SelectQuery.php
- src/Traits/CanLimit.php
- src/ValueList.php
Ref https://github.com/shadowhand/latitude/issues/38
This adds a `psalm.xml` file that catches all serious issues, while leaving some (`UntypedParam` + `MissingConstructor` being the main ones) as (that wouldn't stop a hypothetical travis build).
cc @paragonie-scott
> Add Psalm and attendant fixes

- composer.json
Ref https://github.com/shadowhand/latitude/issues/38
Actually adds to Travis.
If you don't want the warnings, you can add `--show-info=false`
> Add Psalm to composer test

- composer.json
Ref https://travis-ci.org/shadowhand/latitude/builds/326580613
This bumps the version of Psalm to include a release that [fixes the bug](https://github.com/vimeo/psalm/commit/3f3c1380eec9d7aa6cd1ce600fadab5e005673c0) that caused the single error.
It also hides Psalm's warnings, which aren't needed in the build output (and caused confusion here).
> Update Psalm and hide warnings

- src/Partial/Parameter.php
- tests/Partial/CriteriaTest.php
- tests/Query/Postgres/UpdateTest.php
- tests/Query/UpdateTest.php
PDO will try to cast boolean and null values to strings, which can
corrupt INSERT/UPDATE queries and mess with boolean comparisons.
Fixes #55
> Output boolean and null values in SQL

- tests/Engine/MySqlTest.php
- tests/Engine/PostgresTest.php
- tests/Engine/SqlServerTest.php
- tests/TestCase.php
- According to the [Fixtures sample code](https://phpunit.de/manual/6.2/en/fixtures.html), the `setUp` method should be `protected`, not `public`.
> Test enhancement

- src/Ruler/Visitor.php
- tests/CriteriaTest.php
It appears that SQL does not like using operators `=` and `!=` when used with `null` values.
They should be replaced by `IS` and `IS NOT`.
> Enhancing string transformation

- src/Ruler/Visitor.php
- tests/CriteriaTest.php
This is the best I could do for now.
The patch is kind of dirty as it **always** encloses `or` parameters with single brackets `(... or ...)`, but this is - if my mind is not playing tricks with me - logically neutral.
Still - I'm not 100% sure if I have covered all possible situations with tests and if these wrapping brackets are actually 100% safe.
Please check.
> Basic grouping support for `or` operator (issue #83).

- docs/engines.md
- src/Engine/BasicEngine.php
- src/Engine/SqliteEngine.php
- src/EngineInterface.php
- src/Partial/Parameter.php
- tests/Engine/SqliteTest.php
Following guidelines provided by @shadowhand this should fix the problem with using small integers as booleans within the SQLite engine.
New tests included.
> Separate SQLite engine due to boolean parameters conversion (#83)

- tests/Engine/MySqlTest.php
- tests/Engine/SqliteTest.php
- Using the `assertSame` to replace `assertEquals` and it can make assert equals strict.
> Using assertSame to make assert equals strict
